// Code generated by Kitex v0.5.2. DO NOT EDIT.

package metavmservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	meta_rpc "github.com/renjs2001/WebManager/kitex_gen/meta_rpc"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetVMInfo(ctx context.Context, req *meta_rpc.VMInfoReq, callOptions ...callopt.Option) (r *meta_rpc.VMInfoResp, err error)
	GetAbversion(ctx context.Context, req *meta_rpc.VersionReq, callOptions ...callopt.Option) (r *meta_rpc.VersionResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMetaVMServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMetaVMServiceClient struct {
	*kClient
}

func (p *kMetaVMServiceClient) GetVMInfo(ctx context.Context, req *meta_rpc.VMInfoReq, callOptions ...callopt.Option) (r *meta_rpc.VMInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVMInfo(ctx, req)
}

func (p *kMetaVMServiceClient) GetAbversion(ctx context.Context, req *meta_rpc.VersionReq, callOptions ...callopt.Option) (r *meta_rpc.VersionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAbversion(ctx, req)
}
