// Code generated by Kitex v0.5.2. DO NOT EDIT.
package metavmservice

import (
	server "github.com/cloudwego/kitex/server"
	meta_rpc "github.com/renjs2001/WebManager/kitex_gen/meta_rpc"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler meta_rpc.MetaVMService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
